skip-check:
  # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
  - CKV_GHA_7
  # Minimize the admission of pods which lack an associated NetworkPolicy
  - CKV2_K8S_6
  # Default namespace is used
  - CKV_K8S_21
  # Image should use digest - disable temporairly
  - CKV_K8S_43
