name: ghcr-cleanup

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        type: boolean
        required: false
        default: true
  schedule:
    - cron: 10 5 * * *

permissions: read-all

jobs:
  delete-untagged-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete orphaned, partial, ghost images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1
        with:
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-partial-images: true
          delete-untagged: true
          dry-run: ${{ github.event.inputs.dry-run || false }}
          package: malware-cryptominer-container-test
          validate: true

      # - name: Delete "br-*" tags older than 1 months
      #   uses: dataaxiom/ghcr-cleanup-action@v1
      #   with:
      #     use-regex: true
      #     dry-run: ${{ github.event.inputs.dry-run || false }}
      #     delete-tags: br-*
      #     older-than: 1 month
      #     package: malware-cryptominer-container-test

      # - name: Test
      #   uses: dataaxiom/ghcr-cleanup-action@v1
      #   with:
      #     dry-run: ${{ github.event.inputs.dry-run || false }}
      #     delete-tags: brxxx
      #     package: malware-cryptominer-container-test
