name: ghcr-cleanup

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        type: boolean
        required: false
        default: true
  schedule:
    - cron: 2 2 2 * *

permissions: read-all

jobs:
  delete-untagged-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete orphaned, partial, ghost images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-partial-images: true
          delete-untagged: true
          dry-run: ${{ github.event.inputs.dry-run || false }}
          package: malware-cryptominer-container-test
          validate: true
