name: ghcr-cleanup-br

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        type: boolean
        required: false
        default: true

permissions: read-all

jobs:
  ghcr-cleanup-br:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete "br-${{ github.head_ref || github.ref_name }}" tag
        if: ${{ github.ref_name != github.event.repository.default_branch }}
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-tags: br-${{ github.head_ref || github.ref_name }}
          dry-run: ${{ github.event.inputs.dry-run || false }}
          package: malware-cryptominer-container-test
