---
name: latex-build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  latex-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run script to build document
        id: build
        run: |
          ./run.sh
          FILE_NAME=$(ls -1 *.tex | sed  -n 's/\(.*\).tex$/\1/p')
          echo "file_name=${FILE_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: latex-build
          path: ${{ steps.build.outputs.file_name }}.*
          retention-days: 1
