---
name: links

on:
  workflow_dispatch:

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Curl
        run: |
          curl -v https://stackoverflow.com/questions/57970896/pod-limit-on-node-aws-eks/57971006 > /dev/null

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: ". --exclude-path CHANGELOG.md"
          fail: true
