---
name: links

on:
  workflow_dispatch:

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Curl
        run: |
          curl -v https://stackoverflow.com/questions/57970896/pod-limit-on-node-aws-eks/57971006 > /dev/null

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 # v2.1.0
        with:
          args: ". --exclude-path CHANGELOG.md"
          fail: true
