---
name: links

on:
  workflow_dispatch:

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Curl
        run: |
          curl -v https://stackoverflow.com/questions/57970896/pod-limit-on-node-aws-eks/57971006 > /dev/null

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        with:
          args: ". --exclude-path CHANGELOG.md"
          fail: true
