name: pr-notification

# https://github.com/slackapi/slack-github-action/issues/269
# https://github.com/ctriolo/action-post-or-update-slack-message-from-cache/

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - ready_for_review
      - closed
  issue_comment:
    types:
      - created
  pull_request_review:
    types:
      - submitted

permissions: read-all

# defaults:
#   run:
#     shell: bash -euxo pipefail {0}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}" | jq -c
  slack-notification:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a PR is opened
    if: (github.event.action == 'opened' && github.event.pull_request.draft == false) || github.event.action == 'ready_for_review'
    steps:
      - name: Post PR summary message to slack
        id: message
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "💡 *${{ github.event.pull_request.user.login }}*: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}> (+${{ github.event.pull_request.additions }}, -${{ github.event.pull_request.deletions }})"

      - name: Cache slack message timestamp
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          # Use any existing file
          path: README.md
          key: slack-message-timestamp-${{ github.event.pull_request.html_url }}-${{ steps.message.outputs.ts }}

  slack-emoji-react:
    runs-on: ubuntu-latest
    name: Adds emoji reaction to slack message when a PR is closed or reviewed
    if: github.event.action == 'closed' || github.event.action == 'submitted'
    steps:
      # gh commands needs to be executed in the repository
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://stackoverflow.com/questions/74640750/github-actions-not-finding-cache
      # I can not use the cache action in this job because the cache is not shared between runs
      - name: Save slack timestamp as an environment variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "SLACK_TIMESTAMP=$(gh cache list --json key --jq '.[].key|capture("${{ github.event.pull_request.html_url }}-(?<x>.+)").x')" | tee -a "${GITHUB_ENV}"

      - name: Decide which emoji to add
        run: |
          # if [[ "${{ github.event.pull_request.merged }}" == "closed" ]]; then
          # if [[ "${{ github.event.merged }}" == "closed" ]]; then
          # github.event.review.state == 'approved' (https://github.com/orgs/community/discussions/25372)

          # if: contains(github.event.comment.html_url, '/pull/')

          if [[ "${{ github.event.action }}" == "closed" ]]; then
            if [[ "${{ github.event.pull_request.merged }}" == "false" ]]; then
              echo "EMOJI=no-entry" >> "${GITHUB_ENV}"
            fi
          elif [[ "${{ github.event.action }}" == "submitted" ]]; then
            if [[ "${{ github.event.review.state }}" == "approved" ]]; then
              echo "EMOJI=white_check_mark" >> "${GITHUB_ENV}"
            elif [[ "${{ github.event.review.state }}" == "changes_requested" ]]; then
              echo "EMOJI=cross_mark" >> "${GITHUB_ENV}"
            elif [[ "${{ github.event.review.state }}" == "commented" ]]; then
              echo "EMOJI=speech_balloon" >> "${GITHUB_ENV}"
            fi
          fi
          echo "EMOJI=speech_balloon" >> "${GITHUB_ENV}"

      - name: React to PR summary message in slack with emoji
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          method: reactions.add
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: "${{ env.SLACK_TIMESTAMP }}"
            name: ${{ env.EMOJI}}
