---
name: Test

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@bec36cf5736d969f1c5191b9fd2052df87675012 # v2.6.0
        with:
          url: https://owncast.online/docs
          cmd_params: '--buffer-size=8192 --max-connections=10 --color=always --rate-limit=1 --max-connections-per-host 3 --exclude="opencollective.com|github.com|example.com|mydomain.com|sitemap" --verbose'
          debug: true
