---
name: Trigger on schedule (cron) event with -refresh-only to open an issue on configuration drift.

on:
  schedule:
    - cron: 0 0 * * *

env:
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

permissions: read-all

jobs:
  tf:
    runs-on: ubuntu-latest

    permissions:
      actions: read # Required to identify workflow run.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      issues: write # Required to open issue.
      id-token: write # Required to identify workflow run.
      pull-requests: write # Required to add comment and label.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Plan TF
        id: provision
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: terraform
          command: plan
          arg-lock: false
          arg-refresh-only: true
          tool: tofu

      - name: Open issue on drift
        if: ${{ steps.provision.outputs.exitcode != 0 }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          diff: ${{ steps.provision.outputs.diff }}
          run: ${{ steps.provision.outputs.run-url }}
          result: ${{ steps.provision.outputs.result }}
          summary: ${{ steps.provision.outputs.summary }}
        run: |
          gh api /repos/{owner}/{repo}/issues \
            --method POST \
            --field title="Configuration drift detected" \
            --field body="[View log.]($run)
          <details><summary>Diff of changes.</summary>

          \`\`\`diff
          $diff
          \`\`\`
          </details>
          <details><summary>$summary</summary>

          \`\`\`hcl
          $result
          \`\`\`
          </details>"
