---
name: tofu-terraform

# Use-cases:
# * Nevel label PR with more then two "tofu" labels because of concurrency: https://github.com/orgs/community/discussions/41518
# * When there is a new commit pushed to the branch with changes in `terraform` directory - run `terraform plan`
# * When PR is merged with changes in `terraform` directory - run `terraform apply`
# * When PR is labeled by `tofu-plan/apply/destroy` with changes in `terraform` directory - run `terraform plan/apply/destroy`
# * When scheduled - run `terraform apply`
# * When manually called using workflow_dispatch - run `terraform plan/apply/destroy`

on:
  workflow_dispatch:
    inputs:
      tofu_command:
        description: tofu main command
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
  push:
    # https://stackoverflow.com/questions/76037078/why-is-my-github-action-on-paths-also-triggered-when-pushing-a-new-tag
    branches:
      - "**"
    paths:
      - terraform/**
  pull_request:
    types: [labeled]
    paths:
      - terraform/**
  schedule:
    - cron: 0 0 * * *

permissions: read-all

env:
  # keep-sorted start
  AWS_REGION: eu-central-1
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  TF_CLI_ARGS_apply: "-auto-approve"
  TF_CLI_ARGS_destroy: "-auto-approve"
  TF_INPUT: "false"
  TF_IN_AUTOMATION: "true"
  TOFU_WORKING_DIRECTORY: terraform
  # keep-sorted end

# Use concurrency to prevent running tofu-terraform simultaneously
concurrency:
  group: tofu-terraform

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  tofu-terraform:
    # If the action is triggered by a pull request event then run it only for labels `tofu-plan/apply/destroy`
    runs-on: ubuntu-latest
    permissions:
      actions: read # Required to identify workflow run
      checks: write # Required to add status summary
      contents: read # Required to checkout repository
      id-token: write # Required to identify workflow run
      pull-requests: write # Required to add comment and label

    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"
          env

      - name: Set variables
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          PR_LABEL: ${{ github.event.label.name }}
          INPUTS_COMMAND: ${{ inputs.tofu_command }}
          GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          # If inputs.tofu_command form workflow_dispatch is set - use it as tofu_command
          if [[ -z "${INPUTS_COMMAND}" ]]; then

            if [[ "${GITHUB_EVENT_NAME}" = "push" ]]; then
              echo "TOFU_COMMAND=plan" | tee -a "${GITHUB_ENV}"
            fi

            # Run after PR is merged
            if [[ "${GITHUB_EVENT_NAME}" = "push" && "${GITHUB_REF_NAME}" = "${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}" ]]; then
              echo "TOFU_COMMAND=apply" | tee -a "${GITHUB_ENV}"
            fi

            case "${PR_LABEL}" in
              tofu-apply)
                echo "TOFU_COMMAND=apply" | tee -a "${GITHUB_ENV}"
                ;;
              tofu-destroy)
                echo "TOFU_COMMAND=destroy" | tee -a "${GITHUB_ENV}"
                ;;
              tofu-plan)
                echo "TOFU_COMMAND=plan" | tee -a "${GITHUB_ENV}"
                ;;
            esac
          else
            echo "TOFU_COMMAND=${INPUTS_COMMAND}" | tee -a "${GITHUB_ENV}"
          fi

      - name: Configure AWS credentials
        if: ${{ env.TOFU_COMMAND != '' }}
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup OpenTofu
        if: ${{ env.TOFU_COMMAND != '' }}
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5

      - name: Checkout repository
        if: ${{ env.TOFU_COMMAND != '' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 💡 Run tofu "${{ env.TOFU_COMMAND }}"
        if: ${{ env.TOFU_COMMAND != '' }}
        env:
          TOFU_COMMAND: ${{ env.TOFU_COMMAND }}
          TOFU_WORKING_DIRECTORY: ${{ env.TOFU_WORKING_DIRECTORY }}
        run: |
          tofu -chdir="${TOFU_WORKING_DIRECTORY}" init
          tofu -chdir="${TOFU_WORKING_DIRECTORY}" "${TOFU_COMMAND}" | ruby -pe 'print Time.now.strftime("[%Y-%m-%d %H:%M:%S] ")'

      - name: Remove label
        if: ${{ github.event.label.name != '' && env.TOFU_COMMAND != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          PR_LABEL: ${{ github.event.label.name }}
        run: gh api "/repos/{owner}/{repo}/issues/${PR_NUMBER}/labels/${PR_LABEL}" --method DELETE
