name: virt-check

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/virt-check.yml

jobs:
  virt-check-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: lspcu
        run: |
          set -eux
          lscpu
          egrep -o '(vmx|svm)' /proc/cpuinfo | sort | uniq
          egrep -wo 'vmx|lm|aes' /proc/cpuinfo  | sort | uniq | sed -e 's/aes/Hardware encryption=Yes (&)/g' -e 's/lm/64 bit cpu=Yes (&)/g' -e 's/vmx/Intel hardware virtualization=Yes (&)/g'
          # apt list --installed
          # dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h
      - name: accelerator
        run: |
          if [[ $(uname) = "Darwin" ]]; then
            echo "accelerator=hvf"
          elif [[ $(uname) = "Linux" ]]; then
            echo "accelerator=kvm"
          fi

  virt-check-mac:
    runs-on: macos-latest
    steps:
      - name: sysctl
        run: |
          set -x
          sysctl kern.hv_support
          sysctl -a | grep machdep.cpu.features
          sysctl -a | grep -o VMX
          df -h /
          brew uninstall --formula ant aws-sam-cli aspell azure-cli cmake composer gcc gradle harfbuzz icu4c kotlin maven mongodb-community@5.0 mongosh mongodb-database-tools node node@18 openjdk openblas php postgresql@14 r sbt selenium-server
          df -h /
          brew uninstall --cask chromedriver firefox google-chrome julia session-manager-plugin soundflower
          # sudo du -sh /* 2>/dev/null || true
          df -h /
          rm -rf /Users/runner/hostedtoolcache/
          df -h /
          brew cleanup -s
          df -h /
          rm -rf "$(brew --cache)"
          df -h /
          brew list --casks
          brew install findutils
          brew list --formula | xargs  -P8 -I {} \
            sh -c "brew info {} | egrep '[0-9]* files, ' | sed 's/^.*[0-9]* files, \(.*\)).*$/{} \1/'" | \
            sort -h -r -k2 - | column -t | grep MB | sort -k2 -g

      - name: accelerator
        run: |
          if [[ $(uname) = "Darwin" ]]; then
            echo "accelerator=hvf"
          elif [[ $(uname) = "Linux" ]]; then
            echo "accelerator=kvm"
          fi
